default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: bookerka_development_new

test:
  <<: *default
  database: bookerka_test_new

production:
  <<: *default
  database: bookerkaproduction_new
